sudo: required
dist: xenial
language: scala

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.10.1/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK && export JAVA_HOME="$JABBA_HOME/jdk/$TRAVIS_JDK" && export PATH="$JAVA_HOME/bin:$PATH" && java -Xmx32m -version

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk

before_script:
  - unset _JAVA_OPTIONS

script:
  - ./scripts/setup-minikube-for-linux.sh && ./scripts/test.sh

env:
  global:
    - TRAVIS_JDK=adopt@1.8.0-222
    - JABBA_HOME=/home/travis/.jabba
